spring.datasource.url=jdbc:mysql://localhost:3306/dispute_db
spring.datasource.username=root
spring.datasource.password=Admin1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081